"""
Report Generation Module
Generates HTML and JSON security assessment reports
"""

import json
from datetime import datetime
from pathlib import Path

class Reporter:
    def __init__(self):
        self.report_dir = Path("reports")
        self.report_dir.mkdir(exist_ok=True)
    
    def generate_html(self, results: dict, output_file: str):
        """Generate HTML security report"""
        
        html_template = '''<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AI Assistant Security Assessment Report</title>
    <style>
        body {{
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            margin: 0;
            padding: 20px;
            background: #f5f5f5;
        }}
        .container {{
            max-width: 1200px;
            margin: 0 auto;
            background: white;
            padding: 40px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
        }}
        .header {{
            border-bottom: 3px solid #007acc;
            padding-bottom: 20px;
            margin-bottom: 30px;
        }}
        h1 {{
            color: #007acc;
            margin: 0;
        }}
        .meta {{
            color: #666;
            font-size: 14px;
            margin-top: 10px;
        }}
        .summary {{
            display: grid;
            grid-template-columns: repeat(4, 1fr);
            gap: 20px;
            margin-bottom: 40px;
        }}
        .summary-card {{
            padding: 20px;
            border-radius: 8px;
            text-align: center;
        }}
        .critical {{ background: #ffebee; border-left: 4px solid #c62828; }}
        .high {{ background: #fff3e0; border-left: 4px solid #ef6c00; }}
        .medium {{ background: #fff9c4; border-left: 4px solid #f9a825; }}
        .low {{ background: #e8f5e9; border-left: 4px solid #43a047; }}
        .summary-card h2 {{
            margin: 0;
            font-size: 36px;
        }}
        .summary-card p {{
            margin: 5px 0 0 0;
            color: #666;
        }}
        .vulnerability {{
            border: 1px solid #ddd;
            border-radius: 8px;
            padding: 20px;
            margin-bottom: 20px;
        }}
        .vulnerability h3 {{
            margin-top: 0;
        }}
        .severity-badge {{
            display: inline-block;
            padding: 4px 12px;
            border-radius: 4px;
            font-size: 12px;
            font-weight: bold;
            color: white;
        }}
        .badge-critical {{ background: #c62828; }}
        .badge-high {{ background: #ef6c00; }}
        .badge-medium {{ background: #f9a825; }}
        .badge-low {{ background: #43a047; }}
        .vulnerable {{ color: #c62828; font-weight: bold; }}
        .safe {{ color: #43a047; font-weight: bold; }}
        code {{
            background: #f5f5f5;
            padding: 2px 6px;
            border-radius: 3px;
            font-family: 'Courier New', monospace;
        }}
        .evidence {{
            background: #f5f5f5;
            padding: 15px;
            border-radius: 4px;
            margin-top: 10px;
            font-family: 'Courier New', monospace;
            font-size: 12px;
            overflow-x: auto;
        }}
        .footer {{
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid #ddd;
            text-align: center;
            color: #666;
            font-size: 12px;
        }}
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>🔒 AI Assistant Security Assessment Report</h1>
            <div class="meta">
                <strong>Target:</strong> {target}<br>
                <strong>Date:</strong> {timestamp}<br>
                <strong>Framework:</strong> AASRF v1.0.0
            </div>
        </div>
        
        <div class="summary">
            <div class="summary-card critical">
                <h2>{critical_count}</h2>
                <p>CRITICAL</p>
            </div>
            <div class="summary-card high">
                <h2>{high_count}</h2>
                <p>HIGH</p>
            </div>
            <div class="summary-card medium">
                <h2>{medium_count}</h2>
                <p>MEDIUM</p>
            </div>
            <div class="summary-card low">
                <h2>{low_count}</h2>
                <p>LOW</p>
            </div>
        </div>
        
        <h2>Vulnerability Details</h2>
        {vulnerabilities_html}
        
        <div class="footer">
            Generated by AI Assistant Security Research Framework (AASRF)<br>
            For authorized security research only • Report any issues responsibly
        </div>
    </div>
</body>
</html>'''
        
        # Count vulnerabilities by severity
        critical = sum(1 for v in results["vulnerabilities"] if v.get("severity") == "CRITICAL" and v.get("vulnerable"))
        high = sum(1 for v in results["vulnerabilities"] if v.get("severity") == "HIGH" and v.get("vulnerable"))
        medium = sum(1 for v in results["vulnerabilities"] if v.get("severity") == "MEDIUM" and v.get("vulnerable"))
        low = sum(1 for v in results["vulnerabilities"] if v.get("severity") == "LOW" and v.get("vulnerable"))
        
        # Generate vulnerability HTML
        vuln_html = ""
        for vuln in results["vulnerabilities"]:
            status = "VULNERABLE ✗" if vuln.get("vulnerable") else "SAFE ✓"
            status_class = "vulnerable" if vuln.get("vulnerable") else "safe"
            
            severity = vuln.get("severity", "UNKNOWN")
            badge_class = f"badge-{severity.lower()}"
            
            evidence_html = ""
            if vuln.get("evidence"):
                evidence_html = f'<div class="evidence">{vuln["evidence"][:200]}...</div>'
            
            vuln_html += f'''
            <div class="vulnerability">
                <h3>
                    {vuln.get("test_name", "Unknown Test")}
                    <span class="severity-badge {badge_class}">{severity}</span>
                </h3>
                <p><strong>Status:</strong> <span class="{status_class}">{status}</span></p>
                <p><strong>CVE/Reference:</strong> {vuln.get("cve", "N/A")}</p>
                <p><strong>Description:</strong> {vuln.get("description", "No description")}</p>
                {evidence_html}
            </div>
            '''
        
        # Fill template
        html_content = html_template.format(
            target=results.get("target", "Unknown"),
            timestamp=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            critical_count=critical,
            high_count=high,
            medium_count=medium,
            low_count=low,
            vulnerabilities_html=vuln_html
        )
        
        # Write file
        output_path = self.report_dir / output_file
        with open(output_path, 'w') as f:
            f.write(html_content)
        
        return str(output_path)
    
    def generate_json(self, results: dict, output_file: str):
        """Generate JSON report"""
        output_path = self.report_dir / output_file
        with open(output_path, 'w') as f:
            json.dump(results, f, indent=2)
        return str(output_path)
